spring.application.name=lira_api


spring.datasource.url=jdbc:mysql://localhost:3306/projeto_individual
spring.datasource.username=root
spring.datasource.password=0623

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

aws.s3.bucket-name=your-unique-bucket-name
aws.s3.region=us-east-1

# For local development (Use IAM Roles or Environment variables in production)
aws.access-key=YOUR_ACCESS_KEY
aws.secret-key=YOUR_SECRET_KEY
